# Generated by Django 4.2.11 on 2025-05-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_genrefilmwork_options_alter_filmwork_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmwork',
            name='certificate',
        ),
    ]
